<a href="https://colab.research.google.com/github/abdurrahman16/Numpy--Data-Science/blob/main/Advance_Numpy_Operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [3]:
a= np.arange(24)

In [4]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [5]:
a.size

24

In [6]:
a.ndim

1

In [7]:
a=a.reshape(4,6)

In [8]:
a.ndim

2

In [9]:
a=a.reshape(2,3,4)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [10]:
a.shape

(2, 3, 4)

In [11]:
a.dtype

dtype('int64')

In [15]:
d= np.arange(20, dtype=float)

In [17]:
d.dtype

dtype('float64')

In [18]:
print(d)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]


In [19]:
d.itemsize

8

In [20]:
d[12]

np.float64(12.0)

In [36]:
x= np.arange(0,10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
x[5]

np.int64(5)

In [28]:
x.dtype

dtype('int64')

In [29]:
x[4:8]
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [30]:
arr=np.arange(0,11)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
x[4:9]


array([4, 5, 6, 7, 8])

In [41]:
arr[:4]=20 #broadcasting

In [42]:
arr

array([20, 20, 20, 20,  4,  5,  6,  7,  8,  9, 10])

In [43]:
newarr= np.arange(1,13).reshape(3,4)

In [44]:
newarr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
newarr.shape

(3, 4)

In [46]:
newarr[0]

array([1, 2, 3, 4])

In [48]:
newarr[:,1]

array([ 2,  6, 10])

In [49]:
newarr[1:, 1:3]

array([[ 6,  7],
       [10, 11]])