<a href="https://colab.research.google.com/github/abdurrahman16/Numpy--Data-Science/blob/main/Advance_OOP(Inheritance).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
a= np.array([1,2,5])
print(type(a))
print(a.ndim)
print(a.shape)
print('='*40)


#numpy matrix add and sub

x= np.array([[2,4,6],[5,3,2]], )
y= np.array([[8,6,4],[9,8,7]], )

print(x+y)
print(np.add(x,y))
print(x-y)






<class 'numpy.ndarray'>
1
(3,)
[[10 10 10]
 [14 11  9]]
[[10 10 10]
 [14 11  9]]
[[-6 -2  2]
 [-4 -5 -5]]
