<a href="https://colab.research.google.com/github/abdurrahman16/Numpy--Data-Science/blob/main/numpy_array_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
#rank 2 array slicing
import numpy as np
a= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a,'\n')

#slicing
b=a[:2,1:3]
print(b,'\n')

#modify array
print(b[0,0])
b[0,0]=102
print(b[0,0])
print(b,'\n')
print(a,'\n')



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[2 3]
 [6 7]] 

2
102
[[102   3]
 [  6   7]] 

[[  1 102   3   4]
 [  5   6   7   8]
 [  9  10  11  12]] 

